import * as csstree from 'css-tree';
import { noImportant } from './rules/no-important';
import { noIdSelector } from './rules/no-id-selector';

// Here we activate the rules
const activeRules = [noImportant, noIdSelector]

/**
 * Run the rules on the AST and bound the results
 * @param {Object} ast - AST generated by csstree.parse()
 * @returns {Array} found issues by the rules
 */
const runRules = (ast) => {
  const issues = [];
  activeRules.forEach((rule) => {
    issues.push(...rule(ast));
  });
  return issues;
};

/**
 * Validates the CSS with css-tree
 * 
 * @param {Array} cssContent
 * @returns {Object} { isValid, errors: Map, totalErrors, messages }
 */
export const validateCSSWithCssTree = (cssContent) => {
  try {
    let cssString = '';
    let lineIndexMap = [];

    if (Array.isArray(cssContent)) {
      cssContent.forEach((line, index) => {
        const lineContent = Array.isArray(line) ? line[0] : line;
        lineIndexMap.push(index);
        cssString += (lineContent || '') + '\n';
      });
    } else {
      cssString = cssContent || '';
    }
    const syntaxIssues = [];
    const ast = csstree.parse(cssString, {
      positions: true,
      onParseError: (error) => {
        syntaxIssues.push({
          rule: 'css-syntax',
          severity: 'error',
          message: error.rawMessage || error.message,
          line: error.line,
        });
      },
    });

    const ruleIssues = runRules(ast);

    const errorMap = new Map();
    const allIssues = [...syntaxIssues, ...ruleIssues];

    allIssues.forEach((issues) => {
      let targetLineIndex = 0;
      if (issues.line && issues.line <= lineIndexMap.length) {
        targetLineIndex = lineIndexMap[issues.line  - 1];
      }

      if (!errorMap.has(targetLineIndex)) {
        errorMap.set(targetLineIndex, []);
      }

      errorMap.get(targetLineIndex).push({
        message: issues.message,
        rule: issues.rule,
        severity: issues.severity,
      });
    });

    return {
      isValid: allIssues.length === 0,
      errors: errorMap,
      totalErrors: allIssues.length,
      messages:  allIssues,
    };
  } catch (error) {
    console.error('css-tree validation error:', error);
    return {
      isValid: false,
      errors: new Map(),
      totalErrors: 0,
      messages: [],
    };
  }
};

/**
 * @param {Array}
 * @returns {Array}
 */

export const validateCSS = (CSSCode) => {
  const result = CSSCode.map((line) => {
    const content = Array.isArray(line) ? line[0] : line;
    return [content, 'css'];
  });

  const cssTreeResult = validateCSSWithCssTree(result);
  result.cssValidation = cssTreeResult;

  console.log('CSS validation result:', cssTreeResult);
  return result;
};